### ISSUE TITLE
Text on top of photos

### ISSUE THREAD

**Issue by hackeroonis** [hackjunction/hackplatform#84] opened 2020-03-19 09:23 UTC
At the moment the app has a photo on the front page advertising the event and then a photo on the event page header. In both of these photos, the name of the event is written on top of the photo by the app -> You can't see the photos as well (e.g. if they have the logo of the event or other text) and the same text (logo, event name, dates) is usually already in the photo itself as the photos are usually event banners, ads, etc. 

So could the photos be just photos without the text on top? I understand the text is necessary, but could the text be e.g. under the photo? So not on top of them. And I'm speaking about the both pages (front page and event page).

**Comment by khenriksson** [comment] 2020-05-22 10:54
Duplicate of #83

**Closed by khenriksson** 2020-05-22 10:54 UTC
